import { getLocale } from "../helpers/get-locale";

/**
 * Formats a date-like value as a localized date and time string.
 *
 * Use this when both the calendar date and time should be shown. By default it
 * uses medium date style and short time style, and any provided
 * `Intl.DateTimeFormatOptions` override those defaults.
 *
 * @param value - A `Date`, timestamp, or date string accepted by the JavaScript `Date` constructor.
 * @param options - Optional `Intl.DateTimeFormatOptions` plus a `locale` override.
 * @returns A localized date-time string generated by `Intl.DateTimeFormat`.
 *
 * @example
 * formatDateTime('2026-07-20T14:30:00Z', { locale: 'en-US', timeZone: 'UTC' });
 * // "Jul 20, 2026, 2:30 PM"
 */
export const formatDateTime = (
  value: Date | string | number,
  options?: Intl.DateTimeFormatOptions & { locale?: string }
) => {

  const date = new Date(value);

  const locale = getLocale(options);

  return new Intl.DateTimeFormat(locale, {
    dateStyle: "medium",
    timeStyle: "short",
    ...options
  }).format(date);
};
