import { getLocale } from "../helpers/get-locale";

/**
 * Formats a date-like value as a localized calendar date.
 *
 * Use this for date-only display. By default it returns numeric year, two-digit
 * month, and two-digit day, and any provided `Intl.DateTimeFormatOptions`
 * override those defaults.
 *
 * @param value - A `Date`, timestamp, or date string accepted by the JavaScript `Date` constructor.
 * @param options - Optional `Intl.DateTimeFormatOptions` plus a `locale` override.
 * @returns A localized date string generated by `Intl.DateTimeFormat`.
 *
 * @example
 * formatDate('2026-07-20', { locale: 'en-US', timeZone: 'UTC' });
 * // "07/20/2026"
 *
 * @example
 * formatDate('2026-07-20', { locale: 'en-GB', month: 'long', timeZone: 'UTC' });
 * // "20 July 2026"
 */
export const formatDate = (
  value: Date | string | number,
  options?: Intl.DateTimeFormatOptions & { locale?: string }
): string => {

  const date = new Date(value);

  const locale = getLocale(options);

  return new Intl.DateTimeFormat(locale, {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    ...options
  }).format(date);
};
